# ------------------------------------------------------------------------------------
# Example HTTP Requests that can be used to test with VSCode REST Client extension 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# ------------------------------------------------------------------------------------

###
# Check server is status
GET http://localhost:8000/ HTTP/1.1

### 
# valid tenant identifier header
GET http://localhost:8000/events HTTP/1.1
X-Tenant-ID: acme_corp

### 
# Invalid tenant identifier header
GET http://localhost:8000/events HTTP/1.1
X-Tenant-ID: unknown

### 
# filter by a specific date range
GET http://localhost:8000/events?start_dt=2025-03-14T00:00:00Z&end_dt=2025-03-14T23:59:59Z HTTP/1.1
X-Tenant-ID: acme_corp

### 
# filter by a specific action and package
GET http://localhost:8000/events?action=download&package=django HTTP/1.1
X-Tenant-ID: acme_corp

### 
# filter by a specific action and package and date range
GET http://localhost:8000/events?action=download&package=django&start_dt=2025-03-14T00:00:00Z&end_dt=2025-03-14T23:59:59Z HTTP/1.1
X-Tenant-ID: acme_corp


### 
# filter by a specific action and package and date range (non UTC)
GET http://localhost:8000/events?action=download&package=django&start_dt=2025-03-14&end_dt=2025-03-14T20:00:00%2B01:00 HTTP/1.1
X-Tenant-ID: acme_corp
